const ACTION_TYPE = {
    ADD_SERVER:'ADD_SERVER',
    ADD_INTERFACE:"ADD_INTERFACE",

    REMOVE_SERVER:"REMOVE_SERVER",
    REMOVE_INTERFACE:'REMOVE_INTERFACE',

    UPDATE_SERVER:"UPDATE_SERVER",
    UPDATE_INTERFACE:"UPDATE_INTERFACE",

    QUERY_SERVER:"QUERY_SERVER",
    QUERY_INTERFACE_ALL:"QUERY_ALL_INTERFACE_ALL",
    QUERY_INTERFACE_DETAIL:"QUERY_INTERFACE_DETAIL"
}

module.exports = {
    ACTION_TYPE
}